### ISSUE TITLE
Add build for MacOS amd64 architecture

### ISSUE THREAD

**Issue by peterjah** [massalabs/massa-sc-tester#19]
**Is your feature request related to a problem? Please describe.**
The simulator binary is not working on macOs arm64 (Apple Silicon powered Macs)

**Describe the solution you'd like**
Produce another binary build with the aarch64-apple-darwin target architecture

**Comment by qdrn** [comment]
I think it's important to provide binaries for the hackathon.

Do you think you can handle that @thomas-senechal ?
Cc @SlnPons

**Comment by thomas-senechal** [comment]
> There are only releases for testnet tags. They probably don't work with M1 but let's make sure and in that case let's fix that. https://github.com/massalabs/massa/releases/tag/TEST.16.0

The binaries doesn't work on M1:
```
% ./massa-node/massa-node
zsh: bad CPU type in executable: ./massa-node/massa-node
```

I will create an issue to add ARM64 support since there is not such issue.

**Comment by thomas-senechal** [comment]
> The binaries doesn't work on M1:
> 
> ```
> % ./massa-node/massa-node
> zsh: bad CPU type in executable: ./massa-node/massa-node
> ```
> 
> I will create an issue to add ARM64 support since there is not such issue.

Done [here](https://github.com/massalabs/massa/issues/3212).

**Comment by qdrn** [comment]
> Done [here](https://github.com/massalabs/massa/issues/3212).

Thanks.
