### ISSUE TITLE
Add ability to choose sender address

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-sc-tester#8]
It would be nice to be able to choose the sender address to simulate different scenarios. For instance as an argument.

**Comment by qdrn** [comment]
Can one of you handle that @AurelienFT @Eitu33 ? I think it's quite easy to do and it would help testing.

**Comment by Eitu33** [comment]
@qdrn it has been done and merged, along with other new features and a `README.md`.

I'll let you close this to make sure that the changes made correspond to your request.

**Comment by qdrn** [comment]
Cool! Sounds good for now. I'll open new issues if I find that something is missing!
